travis:
  secure:
    BINSTAR_TOKEN: nll1RBItOX5sO8bR3Vkh21QjfELTB8D/Y6YHy6nvlZvOZYCOWLvARLfTseWkaHFp1iEQFLuY/PvgoKfbkdXV6ezuS5QLjVxp9oUKbplBPpKydfxZZT7CivSeIPqfsnJZpaYWesgF6/GCA00oTk8WpzTqFweLq7HDUuas+/NwZoDipEDIEP4fVpDWnuvROGBH94Cg8RlSV58x6PbWKCVW1lExCnN17rLY782pVWAp+C+RNI3nv1DNf+rB9L7fTw6dxbteqfC6lDH1QGZKrWbX1t4l/CNwYLtjEnkcf5N8kTkFFMxlo2Fiz9KrKIEM/vnU466FGpMWhdgz+24QB6FAOKwF0rg5GR9ELuEzdeAZt90NbRpLO/5DsmE7IkGNPGEA3C3GRFexx+xvJwe4a/tpv0YmDa8vWkSxeryd9cvK5sefnhtk42pt56D3Uo6YWYXloHiliPZBEumKwowW2W3NoWJDtTJgqOCT0iWZk3iCITw7tHWuj+e5xiTASj/xGmdTXc9G3jaxXBiQAUo52W434Z1KJdgKIGi0Ax7cFKjUq2sqvhAxh70lOQzxoIZmZZHOOW2vtNaRRorZvOkBooHABesrZ0enUERInnNJWN4hlmJkprRElmOv3Jj+bWedEvOwJaY9/7z0QoeM/iU0e3XOOhtYBnREjDcAmJNf2UyFzZA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
